### ISSUE TITLE
Automatically request to enable Accessibility Service

### ISSUE THREAD

**Issue by JavkhlanK** [CraZyLegenD/Vigilante#25]
Currently, the app doesn't request you to enable the accessibility service and doesn't work. It'd help if it automatically opened the screen to activate Vigilante's service

**Comment by CraZyLegenD** [comment]
It does do that, which device you're using?

When you click enable it opens the accessibility settings where you must find vigilante on your own and turn it on manually.

**Comment by CraZyLegenD** [comment]
I mean it's bad user experience to annoy the user to enable it all the time, that's why you have a button that does that functionality.

**Comment by JavkhlanK** [comment]
I'm using a Galaxy A70 running Android 10 (OneUI 2.0). After turning battery optimizations off, the enable/disable button showed disable immediately, so I had to open settings manually and enable the service

**Comment by CraZyLegenD** [comment]
> I'm using a Galaxy A70 running Android 10 (OneUI 2.0). After turning battery optimizations off, the enable/disable button showed disable immediately, so I had to open settings manually and enable the service

Alright, I'll look into that.
Thank you for reporting it.

**Comment by CraZyLegenD** [comment]
Can you try turning on battery optimizations manually then turning them off again to see if the issue is still there?

I couldn't replicate the issue

**Comment by JavkhlanK** [comment]
I tried that, it's still not detecting that the service isn't running.

**Comment by CraZyLegenD** [comment]
> I tried that, it's still not detecting that the service isn't running.

Do you have another phone to test that behavior?
I tried replicating it on Xiaomi, Pixel, Huawei, Sony and LG, i couldn't succed.

Can you tell me maybe the steps?

I did this:
Disable battery optimizations
Enable the service (the button was enable after i turned off battery optimizations)

**Comment by JavkhlanK** [comment]
Sadly, I only have my A70.

Here's what I did (first time after installing the app):
- Disable Battery Optimizations from the app (clicking on the dialog)
- that's it, the button was already at "disable"

What I tried:
- turning battery optimizations on and opening the app again, rejecting to disable optimizations from the app with the dialog, turning them on manually from settings, re-launching Vigilante, still same "disable" button

all that happened while the service was not started (at least what the settings app says)

**Comment by CraZyLegenD** [comment]
> Sadly, I only have my A70.
> 
> Here's what I did (first time after installing the app):
> 
>     * Disable Battery Optimizations from the app (clicking on the dialog)
> 
>     * that's it, the button was already at "disable"
> 
> 
> What I tried:
> 
>     * turning battery optimizations on and opening the app again, rejecting to disable optimizations from the app with the dialog, turning them on manually from settings, re-launching Vigilante, still same "disable" button
> 
> 
> all that happened while the service was not started (at least what the settings app says)

Did you try disabling the service from settings > accessibility services?
If you disabled it, was it still saying that it's enabled (did the button still say disable)?

**Comment by JavkhlanK** [comment]
The settings toggle always worked.

**Comment by CraZyLegenD** [comment]
> The settings toggle always worked.

Do you have other accessibility services turned on besides vigilante?

**Comment by JavkhlanK** [comment]
![Screenshot_20201116-153121_Settings](https://user-images.githubusercontent.com/40118124/99264549-e4f10f80-2820-11eb-96bd-77e9cff77897.png)
This is my settings menu with accessibility services

**Comment by CraZyLegenD** [comment]
Can you turn everything off except vigilante and see if the button behaves like it should and afterwards try to enable others too, if that's the behavior then you helped me find the culprit!

**Comment by JavkhlanK** [comment]
I did that and it works now! So, the bug's fixed now?

**Comment by CraZyLegenD** [comment]
> I did that and it works now! So, the bug's fixed now?

No, you found where's the bug and I'll fix it in the next release.
