### ISSUE TITLE
Lack of languages

### ISSUE THREAD

**Issue by miguelcanosantana** [CraZyLegenD/Vigilante#26]
Language seems will be added in a certain future. I can provide spanish translations.

**Comment by CraZyLegenD** [comment]
Here are the strings needed for translation

https://github.com/CraZyLegenD/Vigilante/blob/master/app/src/main/res/values/strings.xml

**Comment by miguelcanosantana** [comment]
Okey thanks! I'm translating them via Android Studio Locale Editor

**Comment by miguelcanosantana** [comment]
Added a Pull Request for spanish. https://github.com/CraZyLegenD/Vigilante/pull/27

**Comment by CraZyLegenD** [comment]
> Added a Pull Request for spanish. #27

Merged, thanks.
